apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-devops

commonLabels:
  app.kubernetes.io/name: demo-devops
  app.kubernetes.io/part-of: devsu-technical-test

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

images:
  - name: ghcr.io/CHANGE_ME/demo-devops-nodejs
    newTag: latest
